// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/12/2026, 4:01:36 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/ashraf/pokemon_ttrpg/pokemon_ranger_campaign_player_info/pokedex-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ashraf/pokemon_ttrpg/pokemon_ranger_campaign_player_info/pokedex-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ashraf/pokemon_ttrpg/pokemon_ranger_campaign_player_info/pokedex-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ashraf/pokemon_ttrpg/pokemon_ranger_campaign_player_info/pokedex-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ashraf/pokemon_ttrpg/pokemon_ranger_campaign_player_info/pokedex-app/plugins/**/*.{js,ts,mjs}","/home/ashraf/pokemon_ttrpg/pokemon_ranger_campaign_player_info/pokedex-app/composables/**/*.{js,ts,mjs}","/home/ashraf/pokemon_ttrpg/pokemon_ranger_campaign_player_info/pokedex-app/utils/**/*.{js,ts,mjs}","/home/ashraf/pokemon_ttrpg/pokemon_ranger_campaign_player_info/pokedex-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ashraf/pokemon_ttrpg/pokemon_ranger_campaign_player_info/pokedex-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/ashraf/pokemon_ttrpg/pokemon_ranger_campaign_player_info/pokedex-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/ashraf/pokemon_ttrpg/pokemon_ranger_campaign_player_info/pokedex-app/app.config.{js,ts,mjs}","/home/ashraf/pokemon_ttrpg/pokemon_ranger_campaign_player_info/pokedex-app/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;